# .goreleaser.yaml
builds:
  # You can have multiple builds defined as a yaml list
  -
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser

    env:
      - CGO_ENABLED=0

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - linux

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386, amd64 and arm64.
    goarch:
      - amd64

dockers:
  - image_templates:
      - "ghcr.io/nexeck/modbus-proxy:latest"
      - "ghcr.io/nexeck/modbus-proxy:{{ .Tag }}"
    use: buildx
